import type { Metadata } from "next";
import Link from "next/link";
import { PageIntro } from "@/components/PageIntro";
import { isLocale } from "@/lib/content";
import { pageMetadata } from "@/lib/metadata";
import { getSiteData } from "@/lib/site-data";
import { notFound } from "next/navigation";
type Props = { params: Promise<{ locale: string }> };
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { locale } = await params; return isLocale(locale) ? pageMetadata(locale, "resume", "resume") : {}; }
export default async function ResumePage({ params }: Props) { const { locale } = await params; if (!isLocale(locale)) notFound(); const { profile, displaySettings, education, experiences, awards, skills, certificates, projects } = await getSiteData(); const resumePath = profile.resumePath; const resumeProjects = projects.filter((project) => project.resumeVisible); return <div className="section-shell page-shell"><PageIntro eyebrow="RESUME / 简历" title="一页了解我的教育背景、能力与项目实践。" lead="公开版本已隐藏手机号、出生年月和政治面貌；完整联系方式请通过联系页获取。" />{((displaySettings.showResumeDownload && resumePath) || displaySettings.showContact) && <div className="resume-actions">{displaySettings.showResumeDownload && resumePath && <><a className="button button-primary" href={resumePath} download>下载公开简历<span>↓</span></a><a className="button button-link" href={resumePath} target="_blank" rel="noopener noreferrer">新窗口查看<span>↗</span></a></>}{displaySettings.showContact && <Link className="button button-ghost" href={`/${locale}/contact`}>联系我<span>→</span></Link>}</div>}<p className="resume-privacy"><span>PRIVACY</span>公开版本不展示敏感个人信息，也不收集访客表单数据。</p><div className="resume-layout"><aside className="resume-sidebar"><section><span className="section-index">01</span><h2>个人概述</h2><p>{profile.intro}</p></section><section><span className="section-index">02</span><h2>技能</h2><div className="skill-cloud">{skills.map((skill) => <span key={skill.id}>{skill.name}</span>)}</div></section><section><h2>证书</h2><div className="skill-cloud">{certificates.map((item) => <span key={item.id}>{item.name}</span>)}</div></section></aside><div className="resume-main"><section className="resume-section"><span className="section-index">03</span><h2>教育背景</h2>{education.map((item) => <article className="resume-entry" key={item.id}><div><h3>{item.school}</h3><p>{item.degree} · {item.major} · {item.status === "graduated" ? "已毕业" : "在读"}{item.rank ? ` · ${item.rank}` : ""}</p></div><time>{item.period}</time></article>)}</section><section className="resume-section"><span className="section-index">04</span><h2>项目经历</h2>{resumeProjects.map((project) => <article className="resume-entry" key={project.slug}><div><h3><Link href={`/${locale}/projects/${project.slug}`}>{project.title}</Link></h3><p>{project.role.slice(0, 2).join(" · ")}</p><p>{project.summary}</p></div><time>{project.period}</time></article>)}</section><section className="resume-section"><span className="section-index">05</span><h2>经历</h2>{experiences.map((item) => <article className="resume-entry" key={item.id}><div><h3>{item.role} · {item.organization}</h3><ul className="clean-list">{item.bullets.map((bullet) => <li key={bullet}>{bullet}</li>)}</ul></div><time>{item.period}</time></article>)}</section><section className="resume-section"><span className="section-index">06</span><h2>荣誉与奖项</h2><ul className="award-grid">{awards.map((item) => <li key={item.id}>{item.date ? `${item.date} · ` : ""}{item.title}</li>)}</ul></section></div></div></div>; }
