import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { isLocale } from "@/lib/content";
import { getSiteData } from "@/lib/site-data";
import { notFound } from "next/navigation";
type Props = { params: Promise<{ locale: string; slug: string }> };
const statusLabels = { completed: "已完成", ongoing: "进行中", archived: "已归档" };
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { locale, slug } = await params; if (!isLocale(locale)) return {}; const { projects } = await getSiteData(); const project = projects.find((item) => item.slug === slug); if (!project) return {}; const path = `/${locale}/projects/${slug}`; return { title: project.title, description: project.summary, alternates: { canonical: path }, openGraph: { title: project.title, description: project.summary, url: path, locale: "zh_CN", type: "article" } }; }
export default async function ProjectDetailPage({ params }: Props) {
  const { locale, slug } = await params; if (!isLocale(locale)) notFound(); const { projects } = await getSiteData(); const project = projects.find((item) => item.slug === slug); if (!project) notFound(); const index = projects.findIndex((item) => item.slug === slug); const previous = projects[(index - 1 + projects.length) % projects.length]; const next = projects[(index + 1) % projects.length];
  return <article className="section-shell case-page"><header className="case-hero"><div className="case-title"><span className="eyebrow">PROJECT CASE / {String(index + 1).padStart(2, "0")}</span><h1>{project.title}</h1><p>{project.summary}</p><div className="tag-list">{project.skills.map((skill) => <span key={skill}>{skill}</span>)}</div></div><dl className="case-facts"><div><dt>时间</dt><dd>{project.period}</dd></div><div><dt>状态</dt><dd className="status-text">{statusLabels[project.status]}</dd></div><div><dt>我的角色</dt><dd>{project.role.join(" · ")}</dd></div><div><dt>项目分类</dt><dd>{project.category.join(" · ")}</dd></div></dl></header>
    {project.links.length > 0 ? <div className="case-links">{project.links.map((link) => <a key={link.href} href={link.href} target="_blank" rel="noopener noreferrer">{link.label} ↗</a>)}</div> : null}
    <section className="case-section"><span className="section-index">01</span><div><h2>项目背景</h2><p className="case-lead">{project.background}</p></div></section>
    <section className="case-section"><span className="section-index">02</span><div><h2>我的角色</h2><ul className="action-list">{project.role.map((item) => <li key={item}>{item}</li>)}</ul></div></section>
    <section className="case-section"><span className="section-index">03</span><div><h2>核心任务</h2><ul className="action-list">{project.responsibilities.map((item) => <li key={item}>{item}</li>)}</ul></div></section>
    <section className="case-section"><span className="section-index">04</span><div><h2>我做了什么</h2><ol className="question-list">{project.actions.map((item, itemIndex) => <li key={item}><span>{String(itemIndex + 1).padStart(2, "0")}</span>{item}</li>)}</ol></div></section>
    <section className="case-section"><span className="section-index">05</span><div><h2>成果与数据</h2><ul className="outcome-list">{project.results.map((item) => <li key={item}>{item}</li>)}</ul></div></section>
    <section className="case-section evidence-section"><span className="section-index">06</span><div><h2>作品 / 证据展示</h2>{project.gallery.length > 0 ? <div className="gallery-grid">{project.gallery.map((image, itemIndex) => image.url ? <figure key={`${image.alt}-${itemIndex}`}><Image src={image.url} alt={image.alt} width={1200} height={800} sizes="(max-width: 800px) 100vw, 50vw" /><figcaption>{image.caption || image.alt}</figcaption></figure> : null)}</div> : null}<div className="attachment-grid">{project.attachments.map((item) => <article key={item.title}><span>{item.kind}</span><h3>{item.title}</h3>{item.description ? <p>{item.description}</p> : null}{item.href ? <a className="text-link" href={item.href} target="_blank" rel="noopener noreferrer">查看材料<span>↗</span></a> : <small>暂不公开下载</small>}</article>)}{project.attachments.length === 0 && project.gallery.length === 0 ? <p className="evidence-placeholder">该项目暂未添加可公开的图片或附件。</p> : null}</div></div></section>
    <section className="case-section"><span className="section-index">07</span><div><h2>使用技能</h2><div className="skill-cloud">{project.skills.map((skill) => <span key={skill}>{skill}</span>)}</div></div></section>
    <nav className="case-pagination" aria-label="项目翻页"><Link href={`/${locale}/projects/${previous.slug}`}><span>← 上一个项目</span><strong>{previous.title}</strong></Link><Link href={`/${locale}/projects`}>全部项目</Link><Link href={`/${locale}/projects/${next.slug}`}><span>下一个项目 →</span><strong>{next.title}</strong></Link></nav>
  </article>;
}
