import { defineArrayMember, defineField, defineType } from "sanity";

const strings = (name: string, title: string) =>
  defineField({ name, title, type: "array", of: [defineArrayMember({ type: "string" })] });
const text = (name: string, title: string) => defineField({ name, title, type: "text", rows: 4 });
const order = defineField({ name: "order", title: "排序", type: "number", initialValue: 0 });

const attachment = defineType({ name: "projectAttachment", title: "项目附件 / 证据", type: "object", fields: [defineField({ name: "title", title: "名称", type: "string" }), defineField({ name: "kind", title: "类型", type: "string", options: { list: ["report", "presentation", "system", "research", "other"] } }), text("description", "说明"), defineField({ name: "href", title: "公开链接（可选）", type: "url" })] });
const galleryItem = defineType({ name: "projectGalleryItem", title: "项目图片", type: "image", options: { hotspot: true }, fields: [defineField({ name: "alt", title: "替代文字", type: "string" }), defineField({ name: "caption", title: "说明", type: "string" })] });
const projectLink = defineType({ name: "projectLink", title: "项目链接", type: "object", fields: [defineField({ name: "label", title: "链接名称", type: "string" }), defineField({ name: "href", title: "地址", type: "url" }), defineField({ name: "type", title: "类型", type: "string", options: { list: ["website", "github", "document", "demo"] } })] });
const mediaAsset = defineType({ name: "mediaAsset", title: "素材库", type: "document", fields: [defineField({ name: "title", title: "素材名称", type: "string", validation: (rule) => rule.required() }), defineField({ name: "category", title: "分类", type: "string", options: { list: ["证书", "项目材料", "简历", "图片", "演示文稿", "其他"] } }), defineField({ name: "image", title: "图片", type: "image", options: { hotspot: true } }), defineField({ name: "file", title: "文件", type: "file", options: { accept: "application/pdf,.doc,.docx,.ppt,.pptx,.xls,.xlsx,.zip" } }), text("description", "说明")], preview: { select: { title: "title", subtitle: "category", media: "image" } } });
const mediaReferences = () => defineField({ name: "media", title: "关联素材", type: "array", description: "先在「素材库」上传，再从这里选择；同一素材可在多处复用。", of: [defineArrayMember({ type: "reference", to: [{ type: "mediaAsset" }] })] });

const project = defineType({ name: "project", title: "项目案例", type: "document", fields: [defineField({ name: "title", title: "项目名称", type: "string", validation: (rule) => rule.required() }), defineField({ name: "slug", title: "网址标识", type: "slug", options: { source: "title", maxLength: 96 }, validation: (rule) => rule.required() }), defineField({ name: "category", title: "项目分类", type: "array", of: [defineArrayMember({ type: "string" })], options: { list: ["cross-border", "aigc", "digital-trade", "product", "data-research", "rural-research"] } }), defineField({ name: "status", title: "状态", type: "string", options: { list: [{ title: "已完成", value: "completed" }, { title: "进行中", value: "ongoing" }, { title: "已归档", value: "archived" }] } }), defineField({ name: "period", title: "项目时间", type: "string" }), strings("role", "我的角色"), text("summary", "项目摘要"), text("background", "项目背景"), strings("responsibilities", "核心任务"), strings("actions", "我做了什么"), strings("results", "成果与数据"), strings("skills", "使用技能"), defineField({ name: "gallery", title: "作品 / 证据图片", type: "array", of: [defineArrayMember({ type: "projectGalleryItem" })] }), defineField({ name: "attachments", title: "作品 / 证据材料", type: "array", of: [defineArrayMember({ type: "projectAttachment" })] }), defineField({ name: "links", title: "公开链接", type: "array", of: [defineArrayMember({ type: "projectLink" })] }), mediaReferences(), defineField({ name: "featured", title: "首页精选", type: "boolean", initialValue: false }), defineField({ name: "resumeVisible", title: "在简历展示", type: "boolean", initialValue: true }), order], preview: { select: { title: "title", subtitle: "period" } } });
const profile = defineType({ name: "profile", title: "个人资料", type: "document", fields: [defineField({ name: "name", title: "姓名", type: "string" }), defineField({ name: "latinName", title: "英文姓名", type: "string" }), defineField({ name: "monogram", title: "姓名缩写", type: "string" }), defineField({ name: "professionalTitle", title: "职业定位", type: "string" }), text("valueProposition", "一句话价值主张"), text("intro", "简介"), defineField({ name: "location", title: "所在地", type: "string" }), defineField({ name: "availability", title: "求职状态", type: "string" }), defineField({ name: "email", title: "邮箱", type: "string" }), defineField({ name: "github", title: "GitHub", type: "url" }), defineField({ name: "site", title: "网站地址", type: "url" }), defineField({ name: "resumeFile", title: "公开简历文件", type: "file", description: "上传并发布新版简历后，网站的下载与查看入口会自动使用此文件。", options: { accept: "application/pdf,.doc,.docx" } }), defineField({ name: "heroIllustration", title: "首页卡通人物", type: "reference", description: "从「素材库」选择一张图片；发布后会显示在首页右侧信息栏。", to: [{ type: "mediaAsset" }] }), strings("highlights", "核心证明"), strings("about", "关于我的段落"), mediaReferences()], preview: { select: { title: "name", subtitle: "professionalTitle" } } });
const displaySettings = defineType({ name: "displaySettings", title: "网站展示设置", type: "document", initialValue: { showHome: true, showProjects: true, showResume: true, showAbout: true, showContact: true, showFooter: true, showGithub: true, showResumeDownload: true, zhixuanNotice: { enabled: true, title: "智选优发已启用新域名", description: "智选优发现已迁移至新的官方网站。后续产品介绍与更新将在新站发布，建议使用并收藏新地址。", url: "https://zhixuanyoufa.myboverse.com/" } }, fields: [defineField({ name: "showHome", title: "显示首页导航", type: "boolean", initialValue: true }), defineField({ name: "showProjects", title: "显示项目导航与入口", type: "boolean", initialValue: true }), defineField({ name: "showResume", title: "显示简历导航与入口", type: "boolean", initialValue: true }), defineField({ name: "showAbout", title: "显示关于导航", type: "boolean", initialValue: true }), defineField({ name: "showContact", title: "显示联系导航与入口", type: "boolean", initialValue: true }), defineField({ name: "showFooter", title: "显示网站页脚", type: "boolean", initialValue: true }), defineField({ name: "showGithub", title: "显示 GitHub 链接", type: "boolean", initialValue: true }), defineField({ name: "showResumeDownload", title: "显示公开简历下载与查看按钮", type: "boolean", initialValue: true }), defineField({ name: "zhixuanNotice", title: "智选优发网址提示", type: "object", description: "在个人官网首页显示智选优发的新站提示；未填写的文本会使用默认内容。", fields: [defineField({ name: "enabled", title: "显示提示", type: "boolean", initialValue: true }), defineField({ name: "title", title: "提示标题", type: "string" }), text("description", "提示说明"), defineField({ name: "url", title: "新站网址", type: "url" })] })], preview: { prepare: () => ({ title: "网站展示设置" }) } });
const siteAppearance = defineType({ name: "siteAppearance", title: "网站样式设置", type: "document", initialValue: { accentColor: "#0d55b8", backgroundColor: "#f4f5f7", textColor: "#111317", fontStyle: "sans", contentWidth: "standard", spacing: "comfortable", headingScale: "standard", bodyScale: "standard" }, fields: [defineField({ name: "accentColor", title: "主色", type: "string", description: "输入六位十六进制色值，例如 #0d55b8。", validation: (rule) => rule.regex(/^#[0-9a-fA-F]{6}$/) }), defineField({ name: "backgroundColor", title: "页面背景色", type: "string", description: "输入六位十六进制色值，例如 #f4f5f7。", validation: (rule) => rule.regex(/^#[0-9a-fA-F]{6}$/) }), defineField({ name: "textColor", title: "主要文字颜色", type: "string", description: "输入六位十六进制色值，例如 #111317。", validation: (rule) => rule.regex(/^#[0-9a-fA-F]{6}$/) }), defineField({ name: "fontStyle", title: "字体风格", type: "string", options: { list: [{ title: "简洁无衬线", value: "sans" }, { title: "阅读感衬线", value: "serif" }], layout: "radio" }, initialValue: "sans" }), defineField({ name: "contentWidth", title: "内容宽度", type: "string", options: { list: [{ title: "标准", value: "standard" }, { title: "宽版", value: "wide" }], layout: "radio" }, initialValue: "standard" }), defineField({ name: "spacing", title: "页面留白", type: "string", options: { list: [{ title: "紧凑", value: "compact" }, { title: "舒展", value: "comfortable" }], layout: "radio" }, initialValue: "comfortable" }), defineField({ name: "headingScale", title: "标题大小", type: "string", options: { list: [{ title: "标准", value: "standard" }, { title: "更大", value: "large" }], layout: "radio" }, initialValue: "standard" }), defineField({ name: "bodyScale", title: "正文字号", type: "string", options: { list: [{ title: "标准", value: "standard" }, { title: "更大", value: "large" }], layout: "radio" }, initialValue: "standard" })], preview: { prepare: () => ({ title: "网站样式设置" }) } });
const education = defineType({ name: "education", title: "教育经历", type: "document", fields: [defineField({ name: "school", title: "学校", type: "string" }), defineField({ name: "degree", title: "学历", type: "string" }), defineField({ name: "major", title: "专业", type: "string" }), defineField({ name: "period", title: "时间", type: "string" }), defineField({ name: "status", title: "状态", type: "string", options: { list: [{ title: "已毕业", value: "graduated" }, { title: "在读", value: "studying" }] } }), defineField({ name: "rank", title: "排名", type: "string" }), text("summary", "说明"), mediaReferences(), order], preview: { select: { title: "school", subtitle: "major" } } });
const experience = defineType({ name: "experience", title: "经历", type: "document", fields: [defineField({ name: "organization", title: "组织", type: "string" }), defineField({ name: "role", title: "角色", type: "string" }), defineField({ name: "period", title: "时间", type: "string" }), text("summary", "概述"), strings("bullets", "经历要点"), mediaReferences(), order], preview: { select: { title: "role", subtitle: "organization" } } });
const award = defineType({ name: "award", title: "荣誉 / 奖项", type: "document", fields: [defineField({ name: "title", title: "奖项名称", type: "string" }), defineField({ name: "issuer", title: "颁发方", type: "string" }), defineField({ name: "date", title: "时间", type: "string" }), text("description", "说明"), defineField({ name: "featured", title: "首页展示", type: "boolean", initialValue: false }), mediaReferences(), order], preview: { select: { title: "title", subtitle: "date" } } });
const skill = defineType({ name: "skill", title: "技能", type: "document", fields: [defineField({ name: "name", title: "技能名称", type: "string" }), defineField({ name: "category", title: "能力类别", type: "string" }), text("description", "说明"), mediaReferences(), order], preview: { select: { title: "name", subtitle: "category" } } });
const certificate = defineType({ name: "certificate", title: "证书", type: "document", fields: [defineField({ name: "name", title: "证书名称", type: "string" }), defineField({ name: "issuer", title: "颁发方", type: "string" }), defineField({ name: "date", title: "时间", type: "string" }), mediaReferences(), order], preview: { select: { title: "name", subtitle: "date" } } });

export const schemaTypes = [attachment, galleryItem, projectLink, mediaAsset, profile, displaySettings, siteAppearance, project, education, experience, award, skill, certificate];
