import { defineArrayMember, defineField, defineType } from "sanity";

const strings = (name: string, title: string) =>
  defineField({ name, title, type: "array", of: [defineArrayMember({ type: "string" })] });
const text = (name: string, title: string) => defineField({ name, title, type: "text", rows: 4 });
const order = defineField({ name: "order", title: "排序", type: "number", initialValue: 0 });

const attachment = defineType({ name: "projectAttachment", title: "项目附件 / 证据", type: "object", fields: [defineField({ name: "title", title: "名称", type: "string" }), defineField({ name: "kind", title: "类型", type: "string", options: { list: ["report", "presentation", "system", "research", "other"] } }), text("description", "说明"), defineField({ name: "href", title: "公开链接（可选）", type: "url" })] });
const galleryItem = defineType({ name: "projectGalleryItem", title: "项目图片", type: "image", options: { hotspot: true }, fields: [defineField({ name: "alt", title: "替代文字", type: "string" }), defineField({ name: "caption", title: "说明", type: "string" })] });
const projectLink = defineType({ name: "projectLink", title: "项目链接", type: "object", fields: [defineField({ name: "label", title: "链接名称", type: "string" }), defineField({ name: "href", title: "地址", type: "url" }), defineField({ name: "type", title: "类型", type: "string", options: { list: ["website", "github", "document", "demo"] } })] });
const mediaAsset = defineType({ name: "mediaAsset", title: "素材库", type: "document", fields: [defineField({ name: "title", title: "素材名称", type: "string", validation: (rule) => rule.required() }), defineField({ name: "category", title: "分类", type: "string", options: { list: ["证书", "项目材料", "简历", "图片", "演示文稿", "其他"] } }), defineField({ name: "image", title: "图片", type: "image", options: { hotspot: true } }), defineField({ name: "file", title: "文件", type: "file", options: { accept: "application/pdf,.doc,.docx,.ppt,.pptx,.xls,.xlsx,.zip" } }), text("description", "说明")], preview: { select: { title: "title", subtitle: "category", media: "image" } } });
const mediaReferences = () => defineField({ name: "media", title: "关联素材", type: "array", description: "先在「素材库」上传，再从这里选择；同一素材可在多处复用。", of: [defineArrayMember({ type: "reference", to: [{ type: "mediaAsset" }] })] });

const project = defineType({ name: "project", title: "项目案例", type: "document", fields: [defineField({ name: "title", title: "项目名称", type: "string", validation: (rule) => rule.required() }), defineField({ name: "slug", title: "网址标识", type: "slug", options: { source: "title", maxLength: 96 }, validation: (rule) => rule.required() }), defineField({ name: "category", title: "项目分类", type: "array", of: [defineArrayMember({ type: "string" })], options: { list: ["cross-border", "aigc", "digital-trade", "product", "data-research", "rural-research"] } }), defineField({ name: "status", title: "状态", type: "string", options: { list: [{ title: "已完成", value: "completed" }, { title: "进行中", value: "ongoing" }, { title: "已归档", value: "archived" }] } }), defineField({ name: "period", title: "项目时间", type: "string" }), strings("role", "我的角色"), text("summary", "项目摘要"), text("background", "项目背景"), strings("responsibilities", "核心任务"), strings("actions", "我做了什么"), strings("results", "成果与数据"), strings("skills", "使用技能"), defineField({ name: "gallery", title: "作品 / 证据图片", type: "array", of: [defineArrayMember({ type: "projectGalleryItem" })] }), defineField({ name: "attachments", title: "作品 / 证据材料", type: "array", of: [defineArrayMember({ type: "projectAttachment" })] }), defineField({ name: "links", title: "公开链接", type: "array", of: [defineArrayMember({ type: "projectLink" })] }), mediaReferences(), defineField({ name: "featured", title: "首页精选", type: "boolean", initialValue: false }), defineField({ name: "resumeVisible", title: "在简历展示", type: "boolean", initialValue: true }), order, defineField({ name: "content", title: "历史兼容数据", type: "legacyProjectContent", hidden: true, readOnly: true }), defineField({ name: "year", title: "历史年份", type: "string", hidden: true, readOnly: true }), defineField({ name: "level", title: "历史项目性质", type: "string", hidden: true, readOnly: true }), defineField({ name: "tags", title: "历史标签", type: "array", of: [defineArrayMember({ type: "string" })], hidden: true, readOnly: true })], preview: { select: { title: "title", subtitle: "period" } } });
const legacyProcessStep = defineType({ name: "legacyProcessStep", title: "历史过程步骤", type: "object", fields: [defineField({ name: "title", title: "步骤名称", type: "string" }), text("text", "步骤说明")] });
const legacyProjectContent = defineType({ name: "legacyProjectContent", title: "历史项目详情", type: "object", fields: [defineField({ name: "title", title: "标题", type: "string" }), defineField({ name: "subtitle", title: "副标题", type: "string" }), text("summary", "摘要"), text("background", "项目背景"), strings("problem", "核心问题"), strings("responsibilities", "我的职责"), defineField({ name: "process", title: "工作过程", type: "array", of: [defineArrayMember({ type: "legacyProcessStep" })] }), strings("outcomes", "项目成果"), text("reflection", "限制与反思"), text("evidenceNote", "证据说明")] });
const profile = defineType({ name: "profile", title: "个人资料", type: "document", fields: [defineField({ name: "name", title: "姓名", type: "string" }), defineField({ name: "latinName", title: "英文姓名", type: "string" }), defineField({ name: "monogram", title: "姓名缩写", type: "string" }), defineField({ name: "professionalTitle", title: "职业定位", type: "string" }), text("valueProposition", "一句话价值主张"), text("intro", "简介"), defineField({ name: "location", title: "所在地", type: "string" }), defineField({ name: "availability", title: "求职状态", type: "string" }), defineField({ name: "email", title: "邮箱", type: "string" }), defineField({ name: "github", title: "GitHub", type: "url" }), defineField({ name: "site", title: "网站地址", type: "url" }), defineField({ name: "resumeFile", title: "公开简历文件", type: "file", description: "上传并发布新版简历后，网站的下载与查看入口会自动使用此文件。", options: { accept: "application/pdf,.doc,.docx" } }), defineField({ name: "heroIllustration", title: "首页卡通人物", type: "reference", description: "从「素材库」选择一张图片；发布后会显示在首页右侧信息栏。", to: [{ type: "mediaAsset" }] }), strings("highlights", "核心证明"), strings("about", "关于我的段落"), mediaReferences()], preview: { select: { title: "name", subtitle: "professionalTitle" } } });
const displaySettings = defineType({ name: "displaySettings", title: "网站展示设置", type: "document", initialValue: { showHome: true, showProjects: true, showBlog: true, showResume: true, showAbout: true, showContact: true, showFooter: true, showGithub: true, showResumeDownload: true, contactTopics: ["求职与岗位沟通", "跨境业务与市场研究", "数据分析与数字化工作流", "项目交流与合作"], zhixuanNotice: { enabled: true, title: "智选优发已启用新域名", description: "智选优发现已迁移至新的官方网站。后续产品介绍与更新将在新站发布，建议使用并收藏新地址。", url: "https://zhixuanyoufa.myboverse.com/" } }, fields: [defineField({ name: "showHome", title: "显示首页导航", type: "boolean", initialValue: true }), defineField({ name: "showProjects", title: "显示项目导航与入口", type: "boolean", initialValue: true }), defineField({ name: "showBlog", title: "显示博客导航", type: "boolean", initialValue: true }), defineField({ name: "showResume", title: "显示简历导航与入口", type: "boolean", initialValue: true }), defineField({ name: "showAbout", title: "显示关于导航", type: "boolean", initialValue: true }), defineField({ name: "showContact", title: "显示联系导航与入口", type: "boolean", initialValue: true }), defineField({ name: "showFooter", title: "显示网站页脚", type: "boolean", initialValue: true }), defineField({ name: "showGithub", title: "显示 GitHub 链接", type: "boolean", initialValue: true }), defineField({ name: "showResumeDownload", title: "显示公开简历下载与查看按钮", type: "boolean", initialValue: true }), strings("contactTopics", "适合联系的主题"), defineField({ name: "zhixuanNotice", title: "智选优发网址提示", type: "object", description: "在个人官网首页显示智选优发的新站提示；未填写的文本会使用默认内容。", fields: [defineField({ name: "enabled", title: "显示提示", type: "boolean", initialValue: true }), defineField({ name: "title", title: "提示标题", type: "string" }), text("description", "提示说明"), defineField({ name: "url", title: "新站网址", type: "url" })] })], preview: { prepare: () => ({ title: "网站展示设置" }) } });
const siteAppearance = defineType({
  name: "siteAppearance",
  title: "网站样式设置",
  type: "document",
  initialValue: { themePreset: "professionalBlue", accentColor: "#0d55b8", backgroundColor: "#f4f5f7", textColor: "#111317", fontStyle: "sans", contentWidth: "standard", spacing: "comfortable", headingScale: "standard", bodyScale: "standard" },
  fieldsets: [
    { name: "theme", title: "全局视觉", options: { collapsible: true, collapsed: false } },
    { name: "customColors", title: "第二步：自定义颜色（仅在选择“自定义主题”后填写）", options: { collapsible: true, collapsed: true } },
    { name: "typography", title: "全局文字", options: { collapsible: true, collapsed: false } },
    { name: "layout", title: "全局布局", options: { collapsible: true, collapsed: false } },
    { name: "navigation", title: "导航栏", options: { collapsible: true, collapsed: true } },
    { name: "home", title: "首页", options: { collapsible: true, collapsed: true } },
    { name: "motion", title: "动效", options: { collapsible: true, collapsed: true } },
  ],
  fields: [
    defineField({ name: "themePreset", title: "整体主题", type: "string", fieldset: "theme", description: "选择后会同时调整按钮、链接、强调文字和页面底色。", options: { list: [{ title: "职业蓝 · 当前风格", value: "professionalBlue" }, { title: "学术墨绿 · 更沉稳", value: "forest" }, { title: "极简石墨 · 更克制", value: "graphite" }, { title: "自定义三色", value: "custom" }], layout: "radio" }, initialValue: "professionalBlue" }),
    defineField({ name: "accentColor", title: "强调色：按钮、链接、标记", type: "string", fieldset: "customColors", description: "例如 #0d55b8。只在“自定义三色”主题下生效。", hidden: ({ parent }) => parent?.themePreset !== "custom", validation: (rule) => rule.regex(/^#[0-9a-fA-F]{6}$/) }),
    defineField({ name: "backgroundColor", title: "底色：整页背景", type: "string", fieldset: "customColors", description: "例如 #f4f5f7。只在“自定义三色”主题下生效。", hidden: ({ parent }) => parent?.themePreset !== "custom", validation: (rule) => rule.regex(/^#[0-9a-fA-F]{6}$/) }),
    defineField({ name: "textColor", title: "正文深色：主要标题与文字", type: "string", fieldset: "customColors", description: "例如 #111317。只在“自定义三色”主题下生效。", hidden: ({ parent }) => parent?.themePreset !== "custom", validation: (rule) => rule.regex(/^#[0-9a-fA-F]{6}$/) }),
    defineField({ name: "fontStyle", title: "正文字体风格", type: "string", fieldset: "typography", description: "影响项目说明、简历与页面正文；导航中的英文标识保持清晰的等宽风格。", options: { list: [{ title: "简洁无衬线 · 求职作品集推荐", value: "sans" }, { title: "阅读感衬线 · 适合研究展示", value: "serif" }], layout: "radio" }, initialValue: "sans" }),
    defineField({ name: "headingScale", title: "大标题尺寸", type: "string", fieldset: "typography", description: "影响首页主标题和各页面标题。", options: { list: [{ title: "标准", value: "standard" }, { title: "更醒目", value: "large" }], layout: "radio" }, initialValue: "standard" }),
    defineField({ name: "bodyScale", title: "正文尺寸", type: "string", fieldset: "typography", description: "影响全站阅读字号；推荐默认“标准”。", options: { list: [{ title: "标准", value: "standard" }, { title: "更易阅读", value: "large" }], layout: "radio" }, initialValue: "standard" }),
    defineField({ name: "contentWidth", title: "内容区域宽度", type: "string", fieldset: "layout", description: "影响首页、项目案例和简历内容的左右展开范围。", options: { list: [{ title: "标准 · 阅读更聚焦", value: "standard" }, { title: "宽版 · 大屏展示更多", value: "wide" }], layout: "radio" }, initialValue: "standard" }),
    defineField({ name: "spacing", title: "模块之间留白", type: "string", fieldset: "layout", description: "影响首页和列表页面每个主要模块的上下间距。", options: { list: [{ title: "紧凑 · 信息密度更高", value: "compact" }, { title: "舒展 · 展示感更强", value: "comfortable" }], layout: "radio" }, initialValue: "comfortable" }),
    defineField({ name: "cornerStyle", title: "圆角等级", type: "string", fieldset: "theme", options: { list: [{ title: "直角", value: "sharp" }, { title: "柔和", value: "soft" }, { title: "圆润", value: "round" }], layout: "radio" }, initialValue: "sharp" }),
    defineField({ name: "shadowStyle", title: "阴影等级", type: "string", fieldset: "theme", options: { list: [{ title: "无阴影", value: "none" }, { title: "轻微", value: "subtle" }, { title: "明显", value: "elevated" }], layout: "radio" }, initialValue: "none" }),
    defineField({ name: "navStyle", title: "背景样式", type: "string", fieldset: "navigation", options: { list: [{ title: "实色", value: "solid" }, { title: "透明", value: "transparent" }], layout: "radio" }, initialValue: "solid" }),
    defineField({ name: "navGlass", title: "毛玻璃效果", type: "boolean", fieldset: "navigation", initialValue: false }), defineField({ name: "navSticky", title: "是否吸顶", type: "boolean", fieldset: "navigation", initialValue: false }), defineField({ name: "navHeight", title: "导航高度", type: "string", fieldset: "navigation", options: { list: [{ title: "紧凑", value: "compact" }, { title: "标准", value: "standard" }, { title: "舒展", value: "tall" }], layout: "radio" }, initialValue: "standard" }),
    defineField({ name: "heroLayout", title: "Hero 布局", type: "string", fieldset: "home", options: { list: [{ title: "文字在左", value: "textFirst" }, { title: "照片在左", value: "photoFirst" }], layout: "radio" }, initialValue: "textFirst" }), defineField({ name: "heroBackground", title: "背景效果", type: "string", fieldset: "home", options: { list: [{ title: "无", value: "none" }, { title: "渐变", value: "gradient" }], layout: "radio" }, initialValue: "none" }),
    defineField({ name: "animationIntensity", title: "动画强度", type: "string", fieldset: "motion", options: { list: [{ title: "关闭", value: "none" }, { title: "轻微", value: "subtle" }, { title: "标准", value: "standard" }], layout: "radio" }, initialValue: "standard" }),
  ],
  preview: { prepare: () => ({ title: "网站样式设置" }) },
});
const education = defineType({ name: "education", title: "教育经历", type: "document", fields: [defineField({ name: "school", title: "学校", type: "string" }), defineField({ name: "degree", title: "学历", type: "string" }), defineField({ name: "major", title: "专业", type: "string" }), defineField({ name: "period", title: "时间", type: "string" }), defineField({ name: "status", title: "状态", type: "string", options: { list: [{ title: "已毕业", value: "graduated" }, { title: "在读", value: "studying" }] } }), defineField({ name: "rank", title: "排名", type: "string" }), text("summary", "说明"), mediaReferences(), order], preview: { select: { title: "school", subtitle: "major" } } });
const experience = defineType({ name: "experience", title: "校园经历", type: "document", fields: [defineField({ name: "organization", title: "组织", type: "string" }), defineField({ name: "role", title: "角色", type: "string" }), defineField({ name: "period", title: "时间", type: "string" }), text("summary", "概述"), strings("bullets", "经历要点"), mediaReferences(), order], preview: { select: { title: "role", subtitle: "organization" } } });
const award = defineType({ name: "award", title: "荣誉 / 奖项", type: "document", fields: [defineField({ name: "title", title: "奖项名称", type: "string" }), defineField({ name: "issuer", title: "颁发方", type: "string" }), defineField({ name: "date", title: "时间", type: "string" }), text("description", "说明"), defineField({ name: "featured", title: "首页展示", type: "boolean", initialValue: false }), mediaReferences(), order], preview: { select: { title: "title", subtitle: "date" } } });
const skill = defineType({ name: "skill", title: "技能", type: "document", fields: [defineField({ name: "name", title: "技能名称", type: "string" }), defineField({ name: "category", title: "能力类别", type: "string" }), text("description", "说明"), mediaReferences(), order], preview: { select: { title: "name", subtitle: "category" } } });
const coreStrength = defineType({ name: "coreStrength", title: "核心能力卡片", type: "document", fields: [defineField({ name: "title", title: "卡片标题", type: "string", validation: (rule) => rule.required() }), text("description", "卡片说明"), defineField({ name: "skillCategory", title: "关联技能类别", type: "string", description: "与“技能”中的能力类别相同的技能会显示在这张卡片下。" }), order], preview: { select: { title: "title", subtitle: "skillCategory" } } });
const blogPost = defineType({ name: "blogPost", title: "博客文章", type: "document", fields: [defineField({ name: "title", title: "标题", type: "string", validation: (rule) => rule.required() }), defineField({ name: "slug", title: "网址标识", type: "slug", options: { source: "title" }, validation: (rule) => rule.required() }), text("excerpt", "摘要"), defineField({ name: "coverImage", title: "封面图片", type: "image", options: { hotspot: true } }), defineField({ name: "body", title: "正文（支持富文本）", type: "array", of: [defineArrayMember({ type: "block", styles: [{ title: "正文", value: "normal" }, { title: "标题 2", value: "h2" }, { title: "标题 3", value: "h3" }], lists: [{ title: "项目符号", value: "bullet" }, { title: "编号", value: "number" }], marks: { decorators: [{ title: "加粗", value: "strong" }, { title: "斜体", value: "em" }], annotations: [{ name: "link", title: "链接", type: "object", fields: [defineField({ name: "href", title: "网址", type: "url" })] }] } }), defineArrayMember({ type: "image", options: { hotspot: true } })] }), defineField({ name: "publishedAt", title: "发布时间", type: "datetime" }), defineField({ name: "sourceType", title: "内容类型", type: "string", options: { list: [{ title: "原创", value: "original" }, { title: "外部分享", value: "external" }] }, initialValue: "original" }), defineField({ name: "sourceUrl", title: "外部内容链接", type: "url" }), defineField({ name: "sourceAuthor", title: "原作者", type: "string" }), defineField({ name: "sourcePlatform", title: "来源平台", type: "string" }), mediaReferences(), order], preview: { select: { title: "title", subtitle: "sourcePlatform", media: "coverImage" } } });
const certificate = defineType({ name: "certificate", title: "证书", type: "document", fields: [defineField({ name: "name", title: "证书名称", type: "string" }), defineField({ name: "issuer", title: "颁发方", type: "string" }), defineField({ name: "date", title: "时间", type: "string" }), mediaReferences(), order], preview: { select: { title: "name", subtitle: "date" } } });

const specialPages = defineType({
  name: "specialPages",
  title: "临时页面访问控制",
  type: "document",
  initialValue: { friendshipEnabled: true, sendYwyEnabled: true },
  fields: [
    defineField({ name: "friendshipEnabled", title: "允许访问 /friendship", type: "boolean", initialValue: true, description: "关闭并发布后，页面地址返回 404。" }),
    defineField({ name: "sendYwyEnabled", title: "允许访问 /send-ywy", type: "boolean", initialValue: true, description: "同时控制 /zh/send-ywy 和 /send-ywy/ 下的图片等素材。关闭并发布后返回 404。" }),
  ],
  preview: { prepare: () => ({ title: "临时页面访问控制" }) },
});

export const schemaTypes = [attachment, galleryItem, projectLink, mediaAsset, legacyProcessStep, legacyProjectContent, profile, displaySettings, siteAppearance, specialPages, project, education, experience, award, skill, coreStrength, blogPost, certificate];
